# Generated by Django 5.2.1 on 2025-06-01 13:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nom du thème')),
                ('css_url', models.URLField(blank=True, help_text='URL du fichier CSS du thème', null=True, validators=[django.core.validators.URLValidator()])),
                ('js_url', models.URLField(blank=True, help_text='URL du fichier JS du thème', null=True, validators=[django.core.validators.URLValidator()])),
                ('is_active', models.BooleanField(default=False, verbose_name='Thème activé')),
            ],
        ),
    ]
