# Generated by Django 5.2.1 on 2025-06-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admintheme',
            name='suggestions',
            field=models.TextField(blank=True, help_text="Suggestions pour améliorer l'accessibilité du thème", null=True, verbose_name="Suggestions d'amélioration"),
        ),
    ]
