# Generated by Django 5.2.1 on 2025-06-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_admintheme_suggestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admintheme',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='admintheme',
            name='suggestions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
